# Site settings
title: Pierre Phaneuf
email: pphaneuf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my little corner of Internet.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pphaneuf.github.io" # the base hostname & protocol for your site
twitter_username: pphaneuf
github_username:  pphaneuf

# Build settings
markdown: kramdown
